"use client";
import Script from "next/script";
import { useEffect,useRef,useState } from "react";

declare global{interface Window{Phaser?:any;__fableFuryGame?:any}}

export default function FableFuryPage(){
 const mountRef=useRef<HTMLDivElement|null>(null); const [ready,setReady]=useState(false);
 useEffect(()=>{
  if(!ready||!mountRef.current||!window.Phaser)return; const Phaser=window.Phaser; window.__fableFuryGame?.destroy(true);
  class TrapScene extends Phaser.Scene{
   player:any; art:any; chaser:any; cursors:any; keys:any; healthText:any; messageText:any; chaseText:any;
   worldW=3400; worldH=720; sx=this.worldW/2048; sy=this.worldH/682;
   health=100; invulnerable=false; won=false; isHit=false; jumpsUsed=0; doubleJumpUntil=0; animClock=0; runFrame=0; idleFrame=0; chaseStart=0; lastThreatShake=0;
   runKeys=["harryRun1","harryRun2","harryRun3","harryRun4"]; idleKeys=["harryIdle1","harryIdle2"];
   constructor(){super("TrapScene")}
   wx(n:number){return n*this.sx} wy(n:number){return n*this.sy}
   tex(key:string,w:number,h:number,draw:(g:any)=>void){const g=this.make.graphics({x:0,y:0,add:false});draw(g);g.generateTexture(key,w,h);g.destroy()}
   preload(){
    this.load.image("dungeon","/fablefury/environment/trap-dungeon.png");
    [["harryIdle1","idle-01"],["harryIdle2","idle-02"],["harryRun1","run-01"],["harryRun2","run-02"],["harryRun3","run-03"],["harryRun4","run-04"],["harryJump","jump"],["harryDouble","double%20jump"],["harryHit","hit-01"]].forEach(([k,f])=>this.load.image(k,`/fablefury/characters/harry/${f}.png`));
    [["platformStart","start-platform"],["platformCenter","center-platform"],["platformHangingSmall","hanging-platform-small"],["platformHangingLarge","hanging-platform-large"],["platformTrapBridge","trap-bridge"],["platformRight","right-platform"]].forEach(([k,f])=>this.load.image(k,`/fablefury/platforms/${f}.png`));
    [["spikesLeftArt","spikes-left"],["spikesMiddleArt","spikes-middle"],["sawLargeArt","saw-large"],["sawSmallArt","saw-small"]].forEach(([k,f])=>this.load.image(k,`/fablefury/hazards/${f}.png`));
    this.tex("body",42,66,g=>{g.fillStyle(0xffffff,1);g.fillRect(0,0,42,66)}); this.tex("solid",2,2,g=>{g.fillStyle(0xffffff,.01);g.fillRect(0,0,2,2)});
    this.tex("infernoWall",270,720,g=>{g.fillStyle(0xff2d13,.18);g.fillRect(0,0,270,720);for(let y=20;y<720;y+=72){const w=((y/72)%2)*18;g.fillStyle(0xff3a16,.72);g.fillCircle(128+w,y,118);g.fillStyle(0xff6a1f,.9);g.fillCircle(162-w*.35,y+8,88);g.fillStyle(0xffad24,.96);g.fillCircle(194,y+4,55);g.fillStyle(0xfff2a0,.92);g.fillCircle(220,y,27)}g.fillStyle(0xff8a1f,.82);for(let y=0;y<720;y+=90)g.fillTriangle(170,y+8,265,y+34,182,y+67)});
   }
   resizeArt(key:string){if(!this.art)return;const h=key==="harryDouble"?104:118;this.art.setScale(h/(this.art.height||this.art.frame?.realHeight||1))}
   setArt(key:string){if(!this.art)return;if(this.art.texture.key!==key)this.art.setTexture(key);this.resizeArt(key)}
   piece(key:string,x:number,y:number,w:number,h:number,depth=5){const p=this.add.image(this.wx(x),this.wy(y),key).setOrigin(0,0).setDepth(depth);p.setDisplaySize(this.wx(w),this.wy(h));return p}
   box(group:any,x:number,y:number,w:number,h:number){const b=group.create(this.wx(x+w/2),this.wy(y+h/2),"solid");b.setDisplaySize(this.wx(w),this.wy(h));b.setVisible(false);b.refreshBody();return b}
   platformCue(x:number,y:number,w:number){const g=this.add.rectangle(this.wx(x+w/2),this.wy(y),this.wx(w),10,0xffbd55,.16).setDepth(13).setBlendMode(Phaser.BlendModes.ADD);const l=this.add.rectangle(this.wx(x+w/2),this.wy(y),this.wx(w),3,0xffe2a3,.72).setDepth(14).setBlendMode(Phaser.BlendModes.ADD);this.tweens.add({targets:[g,l],alpha:{from:.38,to:.9},duration:760,yoyo:true,repeat:-1,ease:"Sine.easeInOut"})}
   dangerRect(x:number,y:number,w:number,h:number,strong=true){const f=this.add.rectangle(this.wx(x+w/2),this.wy(y+h/2),this.wx(w),this.wy(h),0xff351c,strong ? .12 : .07).setDepth(15).setBlendMode(Phaser.BlendModes.ADD).setStrokeStyle(strong?5:3,0xff6a2b,.95);const i=this.add.rectangle(this.wx(x+w/2),this.wy(y+h/2),Math.max(4,this.wx(w)-10),Math.max(4,this.wy(h)-10)).setDepth(16).setStrokeStyle(2,0xffd15a,strong ? .8 : .6).setBlendMode(Phaser.BlendModes.ADD);this.tweens.add({targets:[f,i],alpha:{from:strong ? .58 : .42,to:1},duration:strong?340:470,yoyo:true,repeat:-1,ease:"Sine.easeInOut"})}
   dangerLine(x:number,y:number,w:number){const h=this.add.rectangle(this.wx(x+w/2),this.wy(y),this.wx(w),15,0xff3b17,.16).setDepth(15).setBlendMode(Phaser.BlendModes.ADD);const l=this.add.rectangle(this.wx(x+w/2),this.wy(y),this.wx(w),4,0xffb13b,.95).setDepth(16).setBlendMode(Phaser.BlendModes.ADD);this.tweens.add({targets:[h,l],alpha:{from:.48,to:1},duration:360,yoyo:true,repeat:-1})}
   sawCue(cx:number,cy:number,rx:number,ry:number){const o=this.add.ellipse(this.wx(cx),this.wy(cy),this.wx(rx*2.15),this.wy(ry*2.15),0xff3f18,.1).setDepth(15).setBlendMode(Phaser.BlendModes.ADD).setStrokeStyle(4,0xff6a24,.95);const i=this.add.ellipse(this.wx(cx),this.wy(cy),this.wx(rx*1.9),this.wy(ry*1.9)).setDepth(16).setBlendMode(Phaser.BlendModes.ADD).setStrokeStyle(2,0xffd15a,.75);this.tweens.add({targets:[o,i],scale:{from:.96,to:1.04},alpha:{from:.48,to:1},duration:320,yoyo:true,repeat:-1})}
   create(){
    Object.assign(this,{health:100,invulnerable:false,won:false,isHit:false,jumpsUsed:0,doubleJumpUntil:0,animClock:0,runFrame:0,idleFrame:0,chaseStart:this.time.now+900,lastThreatShake:0});
    this.physics.world.setBounds(0,0,this.worldW,this.worldH);this.cameras.main.setBounds(0,0,this.worldW,this.worldH);this.cameras.main.setBackgroundColor("#100c14");
    const bg=this.add.image(0,0,"dungeon").setOrigin(0,0).setDepth(-100);bg.setDisplaySize(this.worldW,this.worldH);this.add.rectangle(this.worldW/2,this.worldH/2,this.worldW,this.worldH,0x08060b,.22).setDepth(-80);
    const pieces:any[]=[["platformStart",0,300,675,120,6],["platformCenter",805,345,230,100,6],["platformHangingSmall",995,220,180,95,7],["platformHangingLarge",1205,235,230,130,7],["platformTrapBridge",1115,405,290,110,7],["platformRight",1380,320,668,115,6]];pieces.forEach(([k,x,y,w,h,d])=>this.piece(k,x,y,w,h,d));
    const spikesLeft=this.piece("spikesLeftArt",500,420,350,100,12),spikesMiddle=this.piece("spikesMiddleArt",990,425,145,95,12),sawLarge=this.piece("sawLargeArt",535,105,190,200,11),sawSmall=this.piece("sawSmallArt",790,165,130,145,11);
    const platformDefs=[[0,327,660],[820,370,195],[1005,244,150],[1215,260,200],[1130,430,255],[1390,346,658]];platformDefs.forEach(([x,y,w])=>this.platformCue(x,y,w));

    // Exact damage readability: what glows is what hurts.
    this.dangerRect(510,448,325,42);this.dangerRect(998,448,126,42);this.sawCue(630,206,72,76);this.sawCue(855,238,49,53);this.dangerLine(480,500,1568);this.dangerRect(1570,305,90,45);this.dangerRect(1660,95,42,255);
    const sgl=this.piece("spikesLeftArt",500,420,350,100,11).setTint(0xff5b2b).setAlpha(.42).setBlendMode(Phaser.BlendModes.ADD),sgm=this.piece("spikesMiddleArt",990,425,145,95,11).setTint(0xff5b2b).setAlpha(.42).setBlendMode(Phaser.BlendModes.ADD);
    const lgl=this.piece("sawLargeArt",535,105,190,200,10).setTint(0xff632b).setAlpha(.34).setBlendMode(Phaser.BlendModes.ADD),lgs=this.piece("sawSmallArt",790,165,130,145,10).setTint(0xff632b).setAlpha(.34).setBlendMode(Phaser.BlendModes.ADD);lgl.setScale(lgl.scaleX*1.05,lgl.scaleY*1.05);lgs.setScale(lgs.scaleX*1.06,lgs.scaleY*1.06);
    this.tweens.add({targets:[spikesLeft,spikesMiddle,sgl,sgm],alpha:{from:.58,to:1},duration:300,yoyo:true,repeat:-1});this.tweens.add({targets:[sawLarge,sawSmall,lgl,lgs],alpha:{from:.58,to:1},duration:250,yoyo:true,repeat:-1});

    const platforms=this.physics.add.staticGroup();platformDefs.forEach(([x,y,w])=>this.box(platforms,x,y,w,y===327||y===346?22:18));
    this.player=this.physics.add.sprite(this.wx(220),this.wy(288),"body");this.player.setAlpha(.001).setCollideWorldBounds(true);this.physics.add.collider(this.player,platforms);this.art=this.add.image(this.player.x,this.player.y,"harryIdle1").setOrigin(.5,1).setDepth(50);this.resizeArt("harryIdle1");
    const hazards=this.physics.add.staticGroup();[[510,448,325,42],[998,448,126,42],[565,140,130,132],[810,187,90,100],[480,505,1568,155],[1570,305,90,45],[1660,95,42,255]].forEach(([x,y,w,h])=>this.box(hazards,x,y,w,h));
    this.chaser=this.physics.add.image(this.wx(14),this.worldH/2,"infernoWall").setDepth(44);this.chaser.body.allowGravity=false;this.chaser.setImmovable(true);this.chaser.setDisplaySize(245,this.worldH+80);this.chaser.body.setSize(115,700).setOffset(150,10);this.chaser.setAlpha(.88).setBlendMode(Phaser.BlendModes.ADD);this.tweens.add({targets:this.chaser,alpha:{from:.72,to:1},scaleX:{from:this.chaser.scaleX*.96,to:this.chaser.scaleX*1.04},duration:190,yoyo:true,repeat:-1});
    const finish=this.physics.add.staticImage(this.wx(2015),this.wy(330),"solid");finish.setDisplaySize(this.wx(42),this.wy(330));finish.setVisible(false);finish.refreshBody();this.physics.add.overlap(this.player,hazards,()=>this.damage(24));this.physics.add.overlap(this.player,this.chaser,()=>this.caught());this.physics.add.overlap(this.player,finish,()=>this.win());
    this.cameras.main.setZoom(1.55);this.cameras.main.startFollow(this.player,true,.14,.12,-95,18);this.cameras.main.setDeadzone(110,70);this.cursors=this.input.keyboard?.createCursorKeys();this.keys=this.input.keyboard?.addKeys("W,A,D,SPACE,R");
    this.healthText=this.add.text(24,20,"Health 100",{fontSize:"22px",color:"#fff",fontStyle:"bold",backgroundColor:"rgba(0,0,0,.45)",padding:{x:9,y:5}}).setScrollFactor(0).setDepth(1000).setScale(.82);
    this.chaseText=this.add.text(640,55,"RUN! THE INFERNO IS COMING!",{fontSize:"30px",color:"#ffcf4a",fontStyle:"bold",backgroundColor:"rgba(90,0,0,.62)",padding:{x:15,y:8}}).setOrigin(.5).setScrollFactor(0).setDepth(1000).setScale(.82);
    this.messageText=this.add.text(640,100,"KEEP MOVING",{fontSize:"21px",color:"#fff",fontStyle:"bold",backgroundColor:"rgba(0,0,0,.28)",padding:{x:10,y:5}}).setOrigin(.5).setScrollFactor(0).setDepth(1000).setScale(.82);this.time.delayedCall(1700,()=>{if(this.chaseText&&this.health>0)this.chaseText.setText("DON'T LET IT CATCH YOU")});
   }
   syncArt(time:number,delta:number){this.art.setPosition(this.player.x,this.player.body.bottom+2);const vx=this.player.body.velocity.x,grounded=this.player.body.blocked.down||this.player.body.touching.down;this.art.setFlipX(vx<-5);if(this.isHit||this.health<=0)return this.setArt("harryHit");if(time<this.doubleJumpUntil)return this.setArt("harryDouble");if(!grounded){this.art.setAngle(0);return this.setArt("harryJump")}this.art.setAngle(0);this.animClock+=delta;if(Math.abs(vx)>10){if(this.animClock>82){this.animClock=0;this.runFrame=(this.runFrame+1)%4}this.setArt(this.runKeys[this.runFrame])}else{if(this.animClock>460){this.animClock=0;this.idleFrame=(this.idleFrame+1)%2}this.setArt(this.idleKeys[this.idleFrame])}}
   doubleJump(time:number){this.player.setVelocityY(-530);this.jumpsUsed=2;this.doubleJumpUntil=time+420;this.setArt("harryDouble");this.tweens.killTweensOf(this.art);this.art.setAngle(0);this.tweens.add({targets:this.art,angle:360,duration:380,ease:"Cubic.easeOut",onComplete:()=>this.art?.setAngle(0)})}
   damage(amount:number){if(this.invulnerable||this.health<=0||this.won)return;this.invulnerable=true;this.isHit=true;this.health=Math.max(0,this.health-amount);this.healthText.setText(`Health ${this.health}`);this.setArt("harryHit");this.art.setTint(0xffb0b0);this.player.setVelocity(-220,-250);this.cameras.main.shake(130,.006);this.time.delayedCall(420,()=>{if(this.health>0){this.art.clearTint();this.isHit=false;this.invulnerable=false}});if(this.health<=0){this.art.setTint(0x777777);this.messageText.setText("DEFEATED — PRESS R");this.chaser?.setVelocityX(0)}}
   caught(){if(this.health<=0||this.won)return;this.health=0;this.isHit=true;this.healthText.setText("Health 0");this.setArt("harryHit");this.art.setTint(0xff704d);this.player.setVelocity(120,-300);this.chaser.setVelocityX(0);this.cameras.main.shake(360,.012);this.chaseText.setText("BURNED!");this.messageText.setText("THE INFERNO GOT YOU — PRESS R")}
   win(){if(this.won)return;this.won=true;this.player.setVelocity(0,0);this.chaser?.setVelocityX(0);this.chaseText.setText("ESCAPED!");this.messageText.setText("VICTORY — PRESS R TO REPLAY")}
   update(time:number,delta:number){if(!this.player||!this.art||!this.keys||!this.cursors)return;this.syncArt(time,delta);if((this.health<=0||this.won)&&Phaser.Input.Keyboard.JustDown(this.keys.R)){this.scene.restart();return}if(this.health<=0||this.won)return;const left=this.cursors.left.isDown||this.keys.A.isDown,right=this.cursors.right.isDown||this.keys.D.isDown;if(left)this.player.setVelocityX(-285);else if(right)this.player.setVelocityX(305);else this.player.setVelocityX(0);const grounded=this.player.body.blocked.down||this.player.body.touching.down;if(grounded)this.jumpsUsed=0;const jump=Phaser.Input.Keyboard.JustDown(this.cursors.up)||Phaser.Input.Keyboard.JustDown(this.keys.W)||Phaser.Input.Keyboard.JustDown(this.keys.SPACE);if(jump&&grounded){this.player.setVelocityY(-555);this.jumpsUsed=1;this.setArt("harryJump")}else if(jump&&this.jumpsUsed<2)this.doubleJump(time);if(time>=this.chaseStart&&this.chaser){const age=time-this.chaseStart,speed=Math.min(252,175+age/260);this.chaser.setVelocityX(speed);const gap=this.player.x-this.chaser.x;if(gap<275&&time-this.lastThreatShake>260){this.lastThreatShake=time;this.cameras.main.shake(90,gap<175 ? .006 : .0025)}if(gap<225&&this.chaseText)this.chaseText.setText("MOVE! MOVE! MOVE!");else if(gap>390&&this.chaseText&&age>1800)this.chaseText.setText("DON'T LET IT CATCH YOU")}}
  }
  window.__fableFuryGame=new Phaser.Game({type:Phaser.AUTO,parent:mountRef.current,width:1280,height:720,backgroundColor:"#100c14",physics:{default:"arcade",arcade:{gravity:{y:1200},debug:false}},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[TrapScene]});
  return()=>{window.__fableFuryGame?.destroy(true);window.__fableFuryGame=undefined};
 },[ready]);
 return <main className="min-h-screen bg-[#09070c] px-4 py-8 text-white sm:px-8"><Script src="https://cdn.jsdelivr.net/npm/phaser@3.90.0/dist/phaser.min.js" strategy="afterInteractive" onLoad={()=>setReady(true)} onReady={()=>setReady(true)}/><div className="mx-auto max-w-7xl"><div className="mb-6"><p className="text-sm font-semibold uppercase tracking-[0.28em] text-orange-300">Playable prototype</p><h1 className="mt-2 text-4xl font-bold sm:text-5xl">Fable Fury: Trap Corridor</h1><p className="mt-3 max-w-3xl text-zinc-300">The glowing red/orange shapes now match the actual damage zones much more tightly.</p></div><div className="overflow-hidden rounded-2xl border border-white/10 bg-black p-2 shadow-2xl"><div ref={mountRef} className="aspect-video w-full overflow-hidden rounded-xl bg-black"/></div><div className="mt-5 grid gap-3 text-sm text-zinc-300 sm:grid-cols-3"><div className="rounded-xl border border-white/10 bg-white/5 p-4">Gold edge = <b className="text-white">standable</b>.</div><div className="rounded-xl border border-white/10 bg-white/5 p-4">Red/orange outline = <b className="text-white">damage zone</b>.</div><div className="rounded-xl border border-white/10 bg-white/5 p-4">Space / W / ↑ jumps; press again in the air to double jump.</div></div></div></main>;
}
