create table if not exists public.fantasy_player_market_snapshots (
  id bigint generated by default as identity primary key,
  espn_league_id bigint not null references public.fantasy_leagues(espn_league_id) on delete cascade,
  espn_player_id bigint not null references public.fantasy_players(espn_player_id) on delete cascade,
  captured_at timestamptz not null default now(),
  source text not null default 'espn',
  fantasy_team_espn_id integer,
  nba_team_espn_id integer,
  default_position_id integer,
  eligible_slots integer[] not null default '{}',
  injury_status text,
  injured boolean,
  percent_owned numeric,
  percent_started numeric,
  average_draft_position numeric,
  auction_value_average numeric,
  unique (espn_league_id, espn_player_id, captured_at)
);

create index if not exists fantasy_player_market_snapshots_player_idx
  on public.fantasy_player_market_snapshots
  (espn_league_id, espn_player_id, captured_at desc);

create index if not exists fantasy_player_market_snapshots_captured_idx
  on public.fantasy_player_market_snapshots
  (espn_league_id, captured_at desc);

alter table public.fantasy_player_market_snapshots enable row level security;

grant select, insert, update, delete
  on public.fantasy_player_market_snapshots to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Preserve the current player-market state as the first historical baseline before
-- later refreshes overwrite fantasy_players with fresher ESPN values.
insert into public.fantasy_player_market_snapshots (
  espn_league_id,
  espn_player_id,
  captured_at,
  source,
  fantasy_team_espn_id,
  nba_team_espn_id,
  default_position_id,
  eligible_slots,
  injury_status,
  injured,
  percent_owned,
  percent_started,
  average_draft_position,
  auction_value_average
)
select
  l.espn_league_id,
  p.espn_player_id,
  coalesce(p.updated_at, now()),
  'legacy-current-row',
  null,
  p.nba_team_espn_id,
  p.default_position_id,
  coalesce(p.eligible_slots, '{}'),
  p.injury_status,
  p.injured,
  p.percent_owned,
  p.percent_started,
  p.average_draft_position,
  p.auction_value_average
from public.fantasy_leagues l
cross join public.fantasy_players p
where p.updated_at is not null
on conflict (espn_league_id, espn_player_id, captured_at) do nothing;
