create table if not exists public.fantasy_draft_intel (
  espn_league_id bigint not null references public.fantasy_leagues(espn_league_id) on delete cascade,
  espn_player_id bigint not null references public.fantasy_players(espn_player_id) on delete cascade,
  recommendation text not null default 'neutral'
    check (recommendation in ('priority','target','neutral','fade','dnd')),
  rank_adjustment integer not null default 0,
  custom_rank numeric,
  draft_at_low numeric,
  draft_at_high numeric,
  first_six_grade text,
  confidence text
    check (confidence is null or confidence in ('low','medium','high')),
  summary text,
  updated_at timestamptz not null default now(),
  primary key (espn_league_id, espn_player_id)
);

create table if not exists public.fantasy_draft_intel_updates (
  id bigint generated by default as identity primary key,
  espn_league_id bigint not null references public.fantasy_leagues(espn_league_id) on delete cascade,
  espn_player_id bigint not null references public.fantasy_players(espn_player_id) on delete cascade,
  observed_at timestamptz not null default now(),
  source_title text,
  source_url text,
  source_type text,
  analysis text not null,
  adjustment_delta integer,
  confidence text
    check (confidence is null or confidence in ('low','medium','high')),
  created_at timestamptz not null default now()
);

create index if not exists fantasy_draft_intel_rank_idx
  on public.fantasy_draft_intel (espn_league_id, custom_rank nulls last, rank_adjustment desc);

create index if not exists fantasy_draft_intel_updates_player_idx
  on public.fantasy_draft_intel_updates (espn_league_id, espn_player_id, observed_at desc);

alter table public.fantasy_draft_intel enable row level security;
alter table public.fantasy_draft_intel_updates enable row level security;

grant select, insert, update, delete on public.fantasy_draft_intel to service_role;
grant select, insert, update, delete on public.fantasy_draft_intel_updates to service_role;
grant usage, select on all sequences in schema public to service_role;
